# Generated by Django 5.1.5 on 2025-01-28 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Duration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_duration", models.IntegerField()),
                ("quantity_lesson_x_week", models.IntegerField()),
                ("minutes", models.FloatField()),
                ("total_lessons", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("normal", models.FloatField()),
                ("institution", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initial_date", models.DateTimeField()),
                ("final_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_created=True, auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("level", models.CharField(max_length=30)),
                ("days_week", models.IntegerField()),
                ("quantity_persons", models.IntegerField()),
                ("initial_date", models.DateTimeField()),
                ("final_date", models.DateTimeField()),
                ("registration_deadline", models.DateTimeField()),
                ("goal", models.TextField()),
                (
                    "duration_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.duration",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.price"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.schedule",
                    ),
                ),
            ],
        ),
    ]
